API_NAME = "AI Medical Symptom Assitant"
API_VERSION = "1.0.0"
DEFAULT_MODEL = "DEEP NEURAL NETWORK"

TOP_K = 3
MIN_CONFIDENCE = 40.0
DISCLAIMER = "THIS IS NOT A SUBSTITUE FOR PROFESSIONAL MEDICAL ADVICE"